[package]
name = "quickestimate"
version = "0.1.0"
authors = ["Jack Arthur Harrhy <me@jackharrhy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
